version: '3.7'

services:
  nuxt:
    image: gerardojunior/nuxtjs:stable
    restart: on-failure
    build: 
      context: .
    volumes:
      - '.:/usr/src/nuxt-app' 
    ports:
      - 3000:3000
    command: 
      "npm run dev"    