version: '3.7'

services: 
  nuxt-app:
    build: ./
    container_name: nuxt-app
    restart: always
    volumes:
      - .:/usr/src/nuxt-app
    ports:
      - "3000:3000"
    command: "npm run dev"  